controller:
  metrics:
    enabled: true
    # serviceMonitor:
    #   additionalLabels:
    #     release: kube-prometheus-stack
    #   enabled: true
  service:
    type: LoadBalancer
  replicaCount: "1"
  ingressClassResource:
    name: nginx-private
    controllerValue: k8s.io/nginx-private
  updateStrategy:
    type: Recreate